workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_BASE_URL: "http://tc-joplin:{{ .Values.service.main.ports.main.port }}"

podOptions:
  hostAliases:
    - ip: 127.0.0.1
      hostnames:
        - tc-joplin
